### ISSUE TITLE
All titles should be sentence case

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanillaframework.io#14]
Titles are currently title case, eg:

- Equal Height
- Getting Started
- Code Snippets
- Inline Logos

They should be sentence case, following our copy style guide:

- Equal height
- Getting started
- Code snippets
- Inline logos
- etc.

**Comment by deadlight** [comment]
First part of fix: https://github.com/ubuntudesign/vanilla-framework/pull/509
