### ISSUE TITLE
Remove example.js from the default template

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanillaframework.io#5]
The documentation builder does not allow for bespoke header inclusions. Therefore the script needs to be added to each doc page.

**Comment by barrymcgee** [comment]
As in.. each example html partial in the `vanilla-framrwork` repo?

**Comment by anthonydillon** [comment]
Indeed, little dirty but will work everywhere.

**Comment by barrymcgee** [comment]
Can you point to where is linked from? Can't seem to find it? 🤔

**Comment by anthonydillon** [comment]
@barrymcgee Sorry its on the other project: 
https://github.com/ubuntudesign/docs.vanillaframework.io/commit/f37678756a67a2fe5be6d0c4affb525427f193bc

**Comment by barrymcgee** [comment]
@anthonydillon Yeah, but.. does that file still even exist? https://github.com/ubuntudesign/docs.vanillaframework.io

**Comment by anthonydillon** [comment]
Doesn't look like it. Not sure what's happened to the project.
